Repository pieforproviders/pieforproviders, pull requests merged in 2020-09, with the labels that each got.

#243 Add address items used for lookup (states, cities, etc.)
  app/models/lookup/city.rb
  app/models/lookup/county.rb
  app/models/lookup/state.rb
  app/models/lookup/zipcode.rb
  db/lookup_data/free_zipcode_data_all_us_counties.csv
  db/lookup_data/free_zipcode_data_all_us_states.csv
  db/lookup_data/free_zipcode_data_all_us_zipcodes.csv
  db/migrate/20200825180000_create_lookup_states.rb
  db/migrate/20200825180100_create_lookup_counties.rb
  db/migrate/20200825180200_create_lookup_cities.rb
  db/migrate/20200825180300_create_lookup_zipcodes.rb
  db/seeds.rb
  db/structure.sql
  lib/tasks/address_lookup_items.rake
  spec/factories/lookup/cities.rb
  spec/factories/lookup/counties.rb
  spec/factories/lookup/states.rb
  spec/factories/lookup/zipcodes.rb
  spec/models/lookup/city_spec.rb
  spec/models/lookup/county_spec.rb
  spec/models/lookup/state_spec.rb
  spec/models/lookup/zipcode_spec.rb
Labels: ruby, tech task

#252 Add LicenseTypes to be used as a common enum
  .github/workflows/ci.yml
  app/controllers/application_controller.rb
  app/models/licenses.rb
  config/locales/en.yml
  config/locales/es.yml
  db/migrate/20200814013700_create_license_type_enum.rb
  db/structure.sql
  spec/models/licenses_spec.rb
  spec/support/api/schemas/license_types.json
Labels: ruby, tech task, translations

#287 Allow users to reset passwords
  app/controllers/passwords_controller.rb
  app/mailers/devise_custom_mailer.rb
  app/views/devise/mailer/_footer.html.erb
  app/views/devise/mailer/_greeting.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/layouts/mailer.html.erb
  client/src/App.js
  client/src/ErrorAlert/ErrorAlert.js
  client/src/ErrorAlert/index.js
  client/src/Login/Login.js
  client/src/PasswordReset/NewPassword.js
  client/src/PasswordReset/PasswordResetRequest.js
  client/src/PasswordReset/index.js
  client/src/ResendToken/ResendToken.js
  client/src/ResendToken/index.js
  client/src/Signup/ConfirmationSent.js
  client/src/_shared/ActionLink.js
  client/src/constants.js
  client/src/i18n/locales/en/index.json
  client/src/i18n/locales/es/index.json
  config/environments/test.rb
  config/initializers/devise.rb
  config/locales/en.yml
  config/locales/es.yml
  config/routes.rb
  package.json
  spec/cypress/app_commands/generate_token.rb
  spec/cypress/app_commands/scenarios/basic.rb
  spec/cypress/app_commands/scenarios/reset_password_token_used.rb
  spec/cypress/integration/resetPassword.spec.js
  spec/cypress/integration/resetPasswordRequest.spec.js
  spec/cypress/support/on-rails.js
  spec/cypress/utils/index.js
  spec/mailers/previews/devise_custom_mailer_preview.rb
Labels: translations
